### PR TITLE
Inline incubating semconv attributes

### PR DESCRIPTION
**Pull request by trask**
Follow-up to @laurit's https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1585#discussion_r1878030973

### CODE REVIEW

**Review by breedx-splk — COMMENTED** [review]
I think I must have missed something in the comment...why is it desirable to copy/duplicate these constants?

**Comment by trask** [comment]
https://github.com/open-telemetry/semantic-conventions-java?tab=readme-ov-file#published-releases

> This artifact has the [-alpha](https://github.com/open-telemetry/opentelemetry-java/blob/main/VERSIONING.md) and comes with no compatibility guarantees. Libraries can use this for testing, but should make copies of the attributes to avoid possible runtime errors from version conflicts.

**Comment by breedx-splk** [comment]
> https://github.com/open-telemetry/semantic-conventions-java?tab=readme-ov-file#published-releases
> 
> > This artifact has the [-alpha](https://github.com/open-telemetry/opentelemetry-java/blob/main/VERSIONING.md) and comes with no compatibility guarantees. Libraries can use this for testing, but should make copies of the attributes to avoid possible runtime errors from version conflicts.

So the entire purpose here is to avoid taking a dependency on an artifact with `-alpha` in the suffix? I'd rather do that than have copies of the values that could deviate from the semconv over time....

Maybe we figure that the tests (which use the `-alpha`) give us enough confidence?

**Comment by trask** [comment]
we're worried about diamond dependency problem where some users will end up depending (transitively) on different irreconcilable versions of the semconv alpha artifact

> Maybe we figure that the tests (which use the `-alpha`) give us enough confidence?

yeah, though it would be interesting to validate this

**Comment by laurit** [comment]
The guidance given in https://github.com/open-telemetry/semantic-conventions-java/blob/main/README.md states that

> Libraries can use this for testing, but should make copies of the attributes to avoid possible runtime errors from version conflicts.

**Review by laurit — APPROVED** [review]

**Comment by trask** [comment]
@breedx-splk I'm going to merge since this is the (current) convention in this repo, but we can revisit

**Pull request merged**
