### PR TITLE
Manually remove from pom.xml the dependencies that have been inlined by the shadow plugin

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
**Description:**

Manually remove from `pom.xml` the dependencies that have been inlined by the shadow plugin as they should no be listed in pom.xml as RUNTIME dependencies

**Existing Issue(s):**

- https://github.com/open-telemetry/opentelemetry-java-contrib/issues/86

**Testing:**

* Invoke `./gradlew :maven-extension:publishToMavenLocal`
* Verify in `~/.m2/repository/io/opentelemetry/contrib/opentelemetry-maven-extension/1.7.0-alpha-SNAPSHOT/opentelemetry-maven-extension-1.7.0-alpha-SNAPSHOT.pom`  that the pom doesn't contain any dependency.
* 
**Documentation:**

N/A

**Outstanding items:**

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
Hello @anuraaga , I'm sorry to bother you with this.
I saw that you are the author of [otel.publish-conventions.gradle.kts](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/v1.6.0/buildSrc/src/main/kotlin/otel.publish-conventions.gradle.kts) so you may know how to configure the [MavenPublication](https://docs.gradle.org/current/dsl/org.gradle.api.publish.maven.MavenPublication.html) to overwrite the dependencies of the generated `pom.xml` and remove them.

The bug is that the dependencies inlined by the Gradle Shadow plugin are unexpectedly listed in the generated pom.xml as RUNTIME dependencies when it is expected that they are not listed in the pom.xml at all.

The proposed fix seems to do the job but I'm not a Gradle person so I would like to get a review on this.

**Comment by anuraaga** [comment]
Sure @cyrille-leclerc let me take a look at this tomorrow

**Comment by trask** [comment]
@cyrille-leclerc welcome to the club of people who ask @anuraaga for shadowJar help 😂

try this:

```
configure<PublishingExtension> {
  (components["java"] as AdhocComponentWithVariants).run {
    withVariantsFromConfiguration(configurations["runtimeElements"]) {
      skip()
    }
  }
}
```

**Comment by cyrille-leclerc** [comment]
Thanks @trask, so we have 2 solutions, yours is way shorter. I have no clue on what's the the most maintainable solution. Maybe @anuraaga  can help decide. @trask's solution sounds appealing as it's compact.

```kotlin
configure<PublishingExtension> {
  (components["java"] as AdhocComponentWithVariants).run {
    withVariantsFromConfiguration(configurations["runtimeElements"]) {
      skip()
    }
  }
}
```

or 

```kotlin
publishing {
    (publications) {
      "maven"(MavenPublication::class) {
            pom {
              withXml {
                val pomNode = asNode()
                val dependenciesNode = (pomNode.get("dependencies") as NodeList)[0] as Node
                val dependencyNodes = dependenciesNode.children() as NodeList
                // the jar dependencies bundled in the uber-jar by the shadow plugin are wrongly added as
                // 'runtime' dependencies in the generated pom.xml instead of being absent this pom.xml.
                // Remove those runtime dependencies from the pom.xml:
                dependencyNodes.removeIf {
                  val dependencyNode = it as Node
                  val scope: String = ((dependencyNode.get("scope") as NodeList)[0] as Node).text()
                  val removeDependency = (scope == "runtime" || scope == "compile")
                  logger.debug("pom.xml remove: $removeDependency dependency $dependencyNode")
                  removeDependency
                }
              }
            }
        }
    }
  }
```

**Review by trask — APPROVED** [review]

**Review by anuraaga — APPROVED** [review]
Thanks!

**Pull request merged**
