### PR TITLE
Enable CLA - test PR

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
@lizthegrey can you pls enable EasyCLA for this repo?

**Comment by SergeyKanzhelev** [comment]
Repo is created based on this request: https://github.com/open-telemetry/community/issues/449

**Comment by lizthegrey** [comment]
EasyCLA added. please rebase/--amend to force it to run.

**Comment by rmfitzpatrick** [comment]
EasyCLA verified w/ https://github.com/open-telemetry/opentelemetry-java-contrib/pull/2.  Thanks @SergeyKanzhelev and @lizthegrey!

**Pull request closed without merging**
